### ISSUE TITLE
Help building wii port

### ISSUE THREAD

**Issue by NyTR0S96** [MaikelChan/SpaceCadetPinball#1]
so I am trying to install pacman via the instructions and when i get to `sudo gdebi devkitpro-pacman.amd64.deb` gdebi gives me the error file not found. and I do have gdebi-core installed.
**EDIT:** so i fixed this issue but now i cant actually build the port. i have the assets in the folder and i get `Makefile:16: /opt/devkitpro/devkitPPC./wii_rules: No such file or directory
make: *** No rule to make target '/opt/devkitpro/devkitPPC./wii_rules'.  Stop.`

**Comment by MaikelChan** [comment]
Based on your other issue, I assume that you managed to build it?

**Comment by NyTR0S96** [comment]
yes it compiles correctly and i have the .dol file however i get the error described in the issue wich i will upload an image to shortly.
