### ISSUE TITLE
Black screen after homebrew logo

### ISSUE THREAD

**Issue by donmor** [MaikelChan/SpaceCadetPinball#10]
I have copied these files to the SD card:
```
sdmc:
    \3DS
        \SpaceCadetPinball.3dsx
        \SpaceCadetPinball
            \PINBALL.DAT
            \PINBALL.EXE
            \PINBALL.HLP
            \PINBALL.CHM
            \PINBALL.INF
            \PINBALL.MID
            \PINBALL2.MID
            \FONT.DAT
            \PINBALL.ogg
            \SOUND1.WAV
            ...
            \SOUND999.WAV
```
and installed the CIA version.

Both 3dsx and CIA got a black screen after homebrew logo. Is something wrong?

**Comment by MaikelChan** [comment]
Hmm, everything looks fine to me. Have you tried to rename the 3DS folder to 3ds? It could be case sensitive.

**Comment by donmor** [comment]
> Hmm, everything looks fine to me. Have you tried to rename the 3DS folder to 3ds? It could be case sensitive.

Having no luck :(

**Comment by MaikelChan** [comment]
I don't know what could be missing. Have you tried if it runs on Citra emulator? You can enable the console output of Citra in the Settings/General/Debug tab/Show log console. If it's not finding a file or something, it should probably appear an error there.

Do your assets work with the PC version? Is it the english version that it's recommended in the instructions of the PC version? (pinball.exe from Windows XP (SHA-1 2A5B525E0F631BB6107639E2A69DF15986FB0D05))

**Comment by donmor** [comment]
Solved by renaming PINBALL.exe to lowercase :)

**Comment by MaikelChan** [comment]
Huh, I actually tried that, about renaming pinball.exe to uppercase because you have it that way, instead of my exe which is lowercase, and it worked anyway, so I didn't mention it. But it seems it that it worked for you. I'm glad then, hope you enjoy it!

**Comment by BPzeBanshee** [comment]
Having this issue as well, however neither renaming the `3ds` folder nor any of the given filenames to their capitalised/uncapitalised variants are making any difference.

Can we get logging support or at least some kind of visual indicator as to what's going wrong?
