### ISSUE TITLE
Stuck on yellow screen (Old 3ds)

### ISSUE THREAD

**Issue by ghost** [MaikelChan/SpaceCadetPinball#18]
So i installed the .3dsx version of the game but it won't launch, it gets to the yellow screen and stays there, forcing my to reboot my system. Other programs, such as 3dsident, work just fine. Can this be fixed? Do i need a different home brew launcher?

Homebrew version: 2.4.0 (Steelhax)

**Comment by korbosoft** [comment]
dude, steelhax is outdated

**Comment by korbosoft** [comment]
@EndLordMC see 3ds.hacks.guide on how to upgrade, **DO _NOT_ USE A VIDEO GUIDE.**

**Comment by ghost** [comment]
The guide worked, thanks :)
