### ISSUE TITLE
3DS ver. freezes if binary is not placed in SD root

### ISSUE THREAD

**Issue by tomrow** [MaikelChan/SpaceCadetPinball#2]
Running the game with its 3DSX outside of the SD card root on real hardware will cause the game to hang at a black screen. If the HOME menu or power button is used to close the game, an ARM11 exception will occur.

**Comment by MaikelChan** [comment]
To be more precise, I'm guessing that it freezes when the SpaceCadetPinball folder is not in the same folder as the executable.  Could you confirm if moving the binary to another place, along with the SpaceCadetPinball folder works?

**Comment by tomrow** [comment]
Yes, it seems it looks in the CWD for the resource folder rather than checking the SD root

**Comment by MaikelChan** [comment]
I've added more detailed instructions on how to place the files when running in original hardware.
