### ISSUE TITLE
What folder structure is expected under Data?

### ISSUE THREAD

**Issue by parkerlreed** [MaikelChan/SpaceCadetPinball#20]
I have tried the contents of FULLTILT/CADET/ and 3D Space Cadet Pinball

With Data/PINBALL.DAT (3D space cadet) the application instantly closes on real Wii hardware

With Data/CADET.DAT (FULLTILT) it launches into a kernel crash. 

Both of these are with the sound data under their own folder like the original releases. 

What release or files is expected here?

**Comment by parkerlreed** [comment]
For anybody else running into this. It wants PINBALL.DAT with all of the sounds in the same folder. They cannot be in the subfolder.

**Comment by MaikelChan** [comment]
As you said, for 3D Pinball, all assets should be in the Data folder. For Full Tilt, I just pushed a new version that makes it compatible and updated the README to specify how to enable the music in this case.
