### ISSUE TITLE
Dragon and Pirate tables

### ISSUE THREAD

**Issue by KrypticKobra** [MaikelChan/SpaceCadetPinball#21]
Was wondering if there is the ability to run the two other Pinball Tables from the FULL TILT! release version.  Namely Dragon and Pirate.  I'm not sure how feasible this is, as I haven't looked into the code.  Please feel free to close this if it is out of scope for this project, and apologies if so.

Thanks!
![maxresdefault](https://github.com/MaikelChan/SpaceCadetPinball/assets/48838110/847fa360-b7f8-4fc1-84e9-52c0b7c3cea5)

![full-tilt-pinball_4](https://github.com/MaikelChan/SpaceCadetPinball/assets/48838110/202dc843-cc68-4b2c-94ed-e33de922ca76)

**Comment by KrypticKobra** [comment]
Ahh, I just realized the project you forked this from doesn't even have those tables decompiled yet.  Closing.

**Comment by MaikelChan** [comment]
It would be really cool, yes, but as you said, no support for those yet.
