### ISSUE TITLE
Please update README statement on SDL

### ISSUE THREAD

**Issue by mardy** [MaikelChan/SpaceCadetPinball#22]
Hi Maikel!
  The readme currently says:

> The PC decompilation uses SDL2 to render the game. This Wii port has been changed to use native GPU rendering with the GX library, as SDL for Wii is considered incomplete, doesn't use the GPU too much and it was really slow.

I don't think it's true anymore. We recently ported SDL2 to the Wii, and it is completely accelerated. :-)

**Comment by MaikelChan** [comment]
Hi!

That's amazing and really good to know. I'll consider trying it for other projects.

I have removed that part from the Readme.

Greetings.
