### ISSUE TITLE
Music runs slow on 3DS

### ISSUE THREAD

**Issue by Sunlitspace542** [MaikelChan/SpaceCadetPinball#5]
I converted PINBALL.MID to an ogg file, and when running in-game it sounds significantly slowed down. I've attached my OGG file here.
[PINBALL.zip](https://github.com/MaikelChan/SpaceCadetPinball/files/7482208/PINBALL.zip)

**Comment by MaikelChan** [comment]
Hi!

It turns out that SDL_Mixer doesn't support audio with a sample rate higher than 44100Hz. Your music is at 48000Hz, so SDL slows it down until reaching 44100Hz. Converting it to any sample rate of 44100 or lower should be running fine. I'll specify this in the readme.
