### ISSUE TITLE
(3DS) CIA build?

### ISSUE THREAD

**Issue by Sunlitspace542** [MaikelChan/SpaceCadetPinball#6]
Can a CIA build be provided? I prefer launching from the home menu and not the Homebrew Launcher.

**Comment by Sunlitspace542** [comment]
also a note, pinball.exe is actually not required for the decompiled game to run.

**Comment by Sunlitspace542** [comment]
Also, is there a way to start it overclocked? It's a bit annoying to have to enter the rosalina menu every time I start the game to overclock and enable l2 so the game runs at the correct speed.

**Comment by MaikelChan** [comment]
Hi!

I just published a new release that includes a CIA, enables high speed mode on New 3DS and fixes several issues.
