### ISSUE TITLE
CIA ver. resource locations?

### ISSUE THREAD

**Issue by tomrow** [MaikelChan/SpaceCadetPinball#9]
I recently installled the CIA version to my system, but it hangs when run, as if it can't find the required files. Which location does it look for resources, so I can put them in the right place?

**Comment by MaikelChan** [comment]
Hi!

You should put all the files, including the original exe (as it also contains some needed resources) in <root_of_sd_card>/3ds/SpaceCadetPinball. It's the same path as when using 3dsx format.

**Comment by tomrow** [comment]
Thanks, I must have missed or forgot the change to absolute paths
